### **Задание на повторение материала

1)Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

2)Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

3)Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

4)Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

5)Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

6)Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

7)Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

8)Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

7)Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [1]:
import numpy as np

In [34]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a3 = a.reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a4 = a.reshape(6,2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [22]:
a1_ = a.reshape(2,6,-1)
a1_

array([[[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

In [23]:
a2_ = a.reshape(3,4, -1)
a2_

array([[[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [25]:
a3_ = a.reshape(4,3,-1)
a3_

array([[[12],
        [13],
        [14]],

       [[15],
        [16],
        [17]],

       [[18],
        [19],
        [20]],

       [[21],
        [22],
        [23]]])

In [30]:
a4_ = a.reshape(6,2,-1)
a4_

array([[[12],
        [13]],

       [[14],
        [15]],

       [[16],
        [17]],

       [[18],
        [19]],

       [[20],
        [21]],

       [[22],
        [23]]])

In [31]:
a5_ = a.reshape(12,1,-1)
a5_

array([[[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]]])

массив a5 нельзя считать одномерным, т.к. он имеет и длину (1) и ширину (12)

In [35]:
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [49]:
m = np.random.randn(12).reshape(4, 3)
m

array([[-0.3830192 ,  0.80624325,  0.93010266],
       [-1.14017151, -0.96403151, -0.34004449],
       [-0.55098854,  0.21858203,  0.3860881 ],
       [ 1.21678831, -0.2291574 ,  0.48051792]])

In [50]:
m.size

12

In [52]:
m = m.reshape(1,12)
m

array([[-0.3830192 ,  0.80624325,  0.93010266, -1.14017151, -0.96403151,
        -0.34004449, -0.55098854,  0.21858203,  0.3860881 ,  1.21678831,
        -0.2291574 ,  0.48051792]])

In [53]:
m.size

12

In [58]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [60]:
b = np.arange(20, 0, -2).reshape(10,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [63]:
a.shape

(10,)

In [65]:
b.shape

(10, 1)

массив b имеет два измерения (плоский), массив а - одно (одномерный)