In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3,4])
b = np.array([5,6,7,8,9])

операции над векторами

In [5]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [6]:
c = np.add(a,b)
c

array([ 5,  7,  9, 11, 13])

In [8]:
a = np.array([0,15,27,0,12])
b = np.array([6,8,-1,12,10])

In [10]:
c = a-b
c

array([ -6,   7,  28, -12,   2])

In [12]:
d = np.subtract(a,b)
d

array([ -6,   7,  28, -12,   2])

Умножение вектора на скаляр

In [13]:
a = np.array([0,1,2,3,4])

In [15]:
c = a*2
c

array([0, 2, 4, 6, 8])

In [17]:
a.dot(-10)

array([  0, -10, -20, -30, -40])

In [19]:
np.dot(a, -10)

array([  0, -10, -20, -30, -40])

Скалярное произведение векторов

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [24]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [25]:
a @ b

32

In [27]:
np.dot(a,b)

32

Операции над матрицами

In [28]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [29]:
B = np.array([
    [5,6,7],
    [8,9,0]
])

In [31]:
C = A + B
C

array([[ 6,  8, 10],
       [12, 14,  6]])

In [33]:
C = np.add(A,B)
C

array([[ 6,  8, 10],
       [12, 14,  6]])

In [35]:
D = A - B
D

array([[-4, -4, -4],
       [-4, -4,  6]])

In [37]:
D = np.subtract(A,B)
D

array([[-4, -4, -4],
       [-4, -4,  6]])

In [39]:
X = A * 3
X

array([[ 3,  6,  9],
       [12, 15, 18]])

In [41]:
X = np.dot(A, 3)
X

array([[ 3,  6,  9],
       [12, 15, 18]])

Умножение матриц

In [42]:
x1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [44]:
x2 = np.array([
    [5,6,7,8],
    [9,8,7,6]
])

In [45]:
x1.shape, x2.shape

((3, 2), (2, 4))

In [48]:
x1.shape[1] == x2.shape[0]

True

In [50]:
Z = np.dot(x1,x2)
Z

array([[23, 22, 21, 20],
       [51, 50, 49, 48],
       [79, 78, 77, 76]])

как получен элемент матрицы Z[0],[0] 

In [52]:
Z[0,0]

23

In [53]:
x1[0,0] * x2[0,0] + x1[0,1] * x2[1, 0]

23

возведение матрицы в квадрат

In [55]:
# матрица должна быть квадратная
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [57]:
np.dot(A,A)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [59]:
np.linalg.matrix_power(A,2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Единичная матрица

In [61]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Умножение матрицы на единичную матрицу 1)

In [62]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [64]:
I = np.eye(2)

In [66]:
np.dot(A,I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Умножение матрицы на единичную матрицу 2)

In [74]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [72]:
I = np.eye(3)

In [76]:
np.dot(I, A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

транспонирование матрицы

In [81]:
A = np.array([
    [1,2],
    [4,5],
    [7,8]
])

In [82]:
At = np.transpose(A)
At

array([[1, 4, 7],
       [2, 5, 8]])

In [84]:
A.T

array([[1, 4, 7],
       [2, 5, 8]])

In [86]:
A1 = np.array([
    [1,2],
    [4,5],
    [7,8]
])

In [88]:
A2 = np.array([
    [1,2],
    [4,5],
    [7,8],
    [9,10]
])

In [89]:
A2t = A2.T

In [91]:
np.dot(A1, A2t)

array([[  5,  14,  23,  29],
       [ 14,  41,  68,  86],
       [ 23,  68, 113, 143]])

Вычисление ранга матрицы и определителя

In [109]:
A = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

In [105]:
np.linalg.det(A)

0.0

In [111]:
np.linalg.matrix_rank(A)

2

In [113]:
B = np.array([
    [7,4,7],
    [19,3,12],
    [1,55,15]
])

In [115]:
np.linalg.det(B)

1897.0000000000005

In [117]:
np.linalg.matrix_rank(B)

3

Вычисление обратной матрицы

In [118]:
B = np.array([
    [7,4,7],
    [19,3,12],
    [1,55,15]
])

In [120]:
B_inv = np.linalg.inv(B)
B_inv

array([[-0.3241961 ,  0.17132314,  0.014233  ],
       [-0.14391144,  0.05166052,  0.02583026],
       [ 0.54928835, -0.20084344, -0.02899315]])

In [121]:
np.linalg.inv(B_inv)

array([[ 7.,  4.,  7.],
       [19.,  3., 12.],
       [ 1., 55., 15.]])