In [2]:
import numpy as np

Автоматическое создание массивов

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
np.arange(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [18]:
np.linspace(0, 20, 15)
# 15 - количество чисел в заданном диапазоне

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [21]:
# В качестве первых двух аргументов - степени числа 10
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

Генерация случайных чисел

In [23]:
np.random.sample()

0.02951384375008126

In [24]:
np.random.sample(4)

array([0.55929948, 0.27936034, 0.37033836, 0.16698561])

In [26]:
np.random.sample((2,4))

array([[0.23915293, 0.17807172, 0.00373937, 0.10049502],
       [0.06541427, 0.49834167, 0.74031191, 0.30035943]])

In [28]:
np.random.sample((10, 5, 4))

array([[[2.33263916e-01, 5.35677159e-01, 3.86074417e-01, 5.51589866e-01],
        [2.72338545e-01, 9.12185645e-01, 1.72073152e-01, 8.36833817e-01],
        [6.38295653e-01, 2.14810550e-01, 3.39919294e-01, 6.99248431e-01],
        [7.67359126e-04, 7.18223545e-01, 9.29217351e-01, 6.54221381e-01],
        [1.16503918e-01, 5.77838159e-02, 7.23086740e-01, 1.23297485e-01]],

       [[1.36200419e-01, 9.15101470e-01, 5.23242542e-01, 5.36573171e-01],
        [4.79672113e-02, 1.26717127e-02, 4.19400381e-01, 8.61942212e-01],
        [3.98573356e-01, 3.67157806e-01, 6.39911176e-01, 8.47657432e-01],
        [8.58087346e-01, 3.22188096e-01, 5.54186906e-01, 5.60242966e-01],
        [1.84519539e-01, 4.71136950e-01, 8.12806060e-01, 8.03210444e-01]],

       [[1.14541833e-02, 4.47420614e-01, 7.49297159e-01, 4.51683084e-01],
        [4.51496050e-01, 2.73782427e-01, 9.40014670e-01, 4.15672549e-01],
        [6.34805920e-01, 8.23835635e-01, 7.27076104e-01, 9.77992316e-01],
        [8.31213292e-01, 5.7896047

In [30]:
# Числа с нормальным распределением (среднее значение - 0, среднеквадратичное отклонение - 1)
np.random.randn(10)

array([ 0.44973479, -1.5505212 ,  0.21725544, -0.08974281, -0.03834845,
        1.28715543, -0.78132132, -0.82425331,  0.34789114, -0.64789251])

In [33]:
np.random.randn(4,3)

array([[-0.83820772, -0.30912139, -0.17970661],
       [-0.25852988,  0.10193902, -0.43721098],
       [-0.87480285,  2.42187058, -0.06763164],
       [-1.34192601,  1.22919869,  0.21772822]])

In [36]:
# генерация целых чисел
np.random.randint(10)

6

In [39]:
np.random.randint(0, 100, 5)

array([75,  8, 40, 50, 15])

In [41]:
np.random.randint(0, 100, (3,4))

array([[35, 76, 28, 67],
       [55, 19, 61, 74],
       [18, 64, 69, 55]])

In [42]:
b = np.array([1,2,3,4,5,6,7,8])

In [45]:
# Выбор случайного элемента из заданного массива
np.random.choice(b)

5

In [47]:
np.random.choice(b, 3)

array([1, 6, 1])

Изменение формы массива

In [49]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
a.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# чтобы решейп применить к начальной матрице
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Соединение массивов

In [57]:
a = np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
b = np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
# соединение по оси х
v = np.vstack((a,b))
v

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
a.shape, b.shape, v.shape

((2, 4), (2, 4), (4, 4))

In [64]:
np.concatenate((a,b), axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.concatenate((a,b), axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [66]:
# соединение по оси у
h = np.hstack((a,b))
h

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [67]:
# соединение по оси z
d = np.dstack((a,b))
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])