In [3]:
import numpy as np

Выборка из массива

In [2]:
a = np.random.randint(0, 20, 10)
a

array([18, 16,  7,  2, 19, 10,  7,  9, 11, 19])

In [4]:
a[a > 10]

array([18, 16, 19, 11, 19])

In [6]:
# логическое И
a[(a > 10) & (a % 2 == 0)]

array([18, 16])

In [8]:
# логическое ИЛИ
a[(a > 10) | (a % 2 == 0)]

array([18, 16,  2, 19, 10, 11, 19])

In [10]:
# Возвращает индекусы чисел, удовлетворяющих условию
np.where(a > 10)

(array([0, 1, 4, 8, 9]),)

In [11]:
# тогда сами числа
a[np.where(a > 10)]

array([18, 16, 19, 11, 19])

In [12]:
a = [1,4,6]
b = [5,2,8]

In [14]:
# Если в условии ИСТИНА, берем эл-т из массива а, если ЛОЖЬ - из массива b
np.where([True, False, True], a, b)

array([1, 2, 6])

Сортировка

In [15]:
a = np.array([
    [1,3,6,2],
    [7,4,5,3],
    [5,8,1,4]
])

In [18]:
# явно указать порядок строк
a[[0, 2, 1],:]

array([[1, 3, 6, 2],
       [5, 8, 1, 4],
       [7, 4, 5, 3]])

In [23]:
# явно указать порядок столбцов
a[:,[0,3,1,2]]

array([[1, 2, 3, 6],
       [7, 3, 4, 5],
       [5, 4, 8, 1]])

In [25]:
a.argsort(axis=0)

array([[0, 0, 2, 0],
       [2, 1, 1, 1],
       [1, 2, 0, 2]])

In [27]:
a[:, 0].argsort()

array([0, 2, 1])

In [29]:
# строки отсортированны в соответствии с 0-м столбцом
a[a[:, 0].argsort(), :]

array([[1, 3, 6, 2],
       [5, 8, 1, 4],
       [7, 4, 5, 3]])

Случайное перемешивание

In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.random.shuffle(a)
a

array([1, 5, 3, 0, 2, 7, 4, 9, 8, 6])

In [37]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
# в двумерном массиве перемешиваются только строки
np.random.shuffle(a)
a

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [41]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [43]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [44]:
np.sum(a)

21

In [46]:
np.sum(a, axis=0)

array([5, 7, 9])

In [47]:
np.sum(a, axis=1)

array([ 6, 15])

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a +10

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное (не матричное) умножение массивов

In [54]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b = np.arange(12, 24).reshape(-1,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Broadcasting (на примере сложения)

1) Совпадает только число столбцов

In [59]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [60]:
b = np.array([1,3])

In [62]:
a + b

array([[2, 5],
       [4, 7],
       [6, 9]])

2) Совпадает только число строк

In [67]:
c = np.array([
    [1],
    [2],
    [3]
])

In [69]:
a + c

array([[2, 3],
       [5, 6],
       [8, 9]])

Статистические ф-ии

In [73]:
a = np.random.randint(0, 15, (3, 4))
a

array([[ 7,  7,  9,  6],
       [ 0,  4, 14,  6],
       [ 6, 14,  4,  6]])

In [74]:
a.min()

0

In [75]:
a.min(axis=0)

array([0, 4, 4, 6])

In [76]:
a.min(axis=1)

array([6, 0, 4])

In [78]:
a.mean()

6.916666666666667

In [79]:
a.mean(axis=1)

array([7.25, 6.  , 7.5 ])

In [80]:
a.std(axis=0)

array([3.09120617, 4.18993503, 4.0824829 , 0.        ])

Запись и чтение из файла

In [81]:
np.save('a.npy', a)

In [82]:
b = np.load('a.npy')
b

array([[ 7,  7,  9,  6],
       [ 0,  4, 14,  6],
       [ 6, 14,  4,  6]])