In [3]:
import numpy as np

In [5]:
b = np.array([1,2,4,6,7])
b

array([1, 2, 4, 6, 7])

In [7]:
b[0]

1

In [9]:
b = np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18]
])
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [12]:
b.shape

(3, 6)

In [14]:
b.ndim

2

In [16]:
b[1][2]

9

In [18]:
b[1,2]

9

In [22]:
b[0:2, 0:3]

array([[1, 2, 3],
       [7, 8, 9]])

In [24]:
c = b[0:2, 0:3]
c

array([[1, 2, 3],
       [7, 8, 9]])

In [29]:
# массив с - часть массива b
c[1, 2] = 9999
c

array([[   1,    2,    3],
       [   7,    8, 9999]])

In [31]:
b

array([[   1,    2,    3,    4,    5,    6],
       [   7,    8, 9999,   10,   11,   12],
       [  13,   14,   15,   16,   17,   18]])